module.exports = {
  docs: [
    'index',
    'readme',
    'contributing',
    {
      type: 'category',
      label: 'Examples',
      link: {
        type: 'doc',
        id: 'examples/index',
      },
      items: [
        {
          type: 'category',
          label: 'Class Diagrams',
          items: [
            'examples/plantuml-class-diagrams-en',
            'examples/plantuml-class-diagrams-nl',
          ],
        },
        {
          type: 'category',
          label: 'Domain Models',
          items: [
            'examples/domain-model-larman-vs-fowler',
            'examples/domeinmodel-larman-vs-fowler',
          ],
        },
        {
          type: 'category',
          label: 'Sequence Diagrams',
          items: [
            'examples/sequence-diagram-example',
          ],
        },
        {
          type: 'category',
          label: 'Design Patterns',
          items: [
            'examples/little-red-riding-hood-sequence-diagrams',
            'examples/roodkapje-sequence-diagrams',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'architecture/plugin-architecture',
      ],
    },
    {
      type: 'category',
      label: 'ADRs',
      link: {
        type: 'doc',
        id: 'adr/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'adr',
        },
      ],
    },
  ],
};
