module.exports = {
  docs: [
    'readme-github',
    'playground',
    {
      type: 'category',
      label: 'Introduction to UML',
      items: [
        'examples/little-red-riding-hood-as-uml-diagrams',
        'examples/roodkapje-in-uml-diagrammen',
        'examples/uml-quiz-multiple-choice',
        'examples/uml-quiz-experimental-syntax',
      ],
    },
    {
      type: 'category',
      label: 'PlantUML',
      items: [
        {
          type: 'category',
          label: 'Class Diagrams',
          items: [
            'examples/plantuml-class-diagrams-en',
            'examples/plantuml-class-diagrams-nl',
            'examples/external-diagram-sources',
            'examples/domain-model-larman-vs-fowler',
            'examples/domeinmodel-larman-vs-fowler',
          ],
        },
        {
          type: 'category',
          label: 'Sequence Diagrams',
          items: [
            'examples/sequence-diagram-example-en',
            'examples/sequence-diagram-example',
          ],
        },
        {
          type: 'category',
          label: 'Activity Diagrams',
          items: [
            'examples/plantuml-activity-diagrams-en',
            'examples/plantuml-activity-diagrams-nl',
          ],
        },
        {
          type: 'category',
          label: 'Domain Storytelling',
          items: [
            'examples/domain-stories',
            'examples/user-story-map-roadmap-textusm',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Mermaid',
      items: [
        {
          type: 'category',
          label: 'Class Diagrams',
          items: [
            'examples/mermaid-class-diagrams',
            'examples/mermaid-class-diagrams-nl',
          ],
        },
        'examples/mermaid-theme-comparison',
      ],
    },
    {
      type: 'category',
      label: 'Plugin Architecture (SGB)',
      items: [
        'architecture/software-guidebook',
      ],
    },
    {
      type: 'category',
      label: 'ADRs',
      link: {
        type: 'doc',
        id: 'adr/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'adr',
        },
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [
        'contributing',
        'definition-of-done',
      ],
    },
  ],
};
