module.exports = {
  docs: [
    'readme',
    {
      type: 'category',
      label: 'Contributing',
      items: [
        'contributing',
        'definition-of-done',
      ],
    },
    {
      type: 'category',
      label: 'Introduction to UML',
      items: [
        'examples/little-red-riding-hood-as-uml-diagrams',
        'examples/roodkapje-in-uml-diagrammen',
      ],
    },
    {
      type: 'category',
      label: 'PlantUML',
      items: [
        'examples/plantuml-class-diagrams-en',
        'examples/plantuml-class-diagrams-nl',
        'examples/domain-model-larman-vs-fowler',
        'examples/domeinmodel-larman-vs-fowler',
        'examples/sequence-diagram-example',
      ],
    },
    {
      type: 'category',
      label: 'Mermaid',
      items: [
        'examples/mermaid-class-diagrams',
        'examples/mermaid-theme-comparison',
      ],
    },
    {
      type: 'category',
      label: 'Software Guidebook',
      items: [
        'architecture/plugin-architecture',
      ],
    },
    {
      type: 'category',
      label: 'ADRs',
      link: {
        type: 'doc',
        id: 'adr/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'adr',
        },
      ],
    },
  ],
};
